<a href="https://colab.research.google.com/github/Swapnapokharkar/Task-5-Data-Science-Liabraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##1st program sorted array
#importing Numpy Library

import numpy as np
a = np.array([[1, 4, 2],
             [3, 4, 6],
             [0, -1, 5]])
print ("Array elements in sorted order:\n",np.sort(a, axis = None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [2]:
#2nd program Exponent value of array
#importing Numpy Library

import numpy as np
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:",np.exp(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [3]:
#3rd program modify existing array
#importing Numpy Library

import numpy as np
a = np.array([1, 2, 5, 3])
a *= 2
print ("Doubled each element of original array:", a)

Doubled each element of original array: [ 2  4 10  6]


In [4]:
#4th program to maximum & minimum elements of array 
#importing Numpy Library

import numpy as np
array = np.array([[1, 5, 6],
               [4, 7, 2],
               [3, 1, 8]])
print ("Largest element is:", array.max())
print ("Row wise maximum elements:",array.min(axis = 0))
print ("Column wise minimum elements:", array.min(axis = 0))


Largest element is: 8
Row wise maximum elements: [1 1 2]
Column wise minimum elements: [1 1 2]


In [5]:
#5th program slicing array
#importing Numpy Library

import numpy as np
array = np.array([[-1, 2, 0, 4],
               [4, -0.5, 6, 0],
               [2.6, 0, 7, 8],
               [3, -7, 4, 2.0]])
                
temp = array[:2, ::2]
print ("array with first 2 rows and alternate" "columns(0 and 2):\n", temp)
cond = array > 0
temp = array[cond]
print ("\n Elements greater than 0:\n", temp)

array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

 Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [6]:
#6th program Creating array from Touple with type float
#importing Numpy Library

import numpy as np 
b = np.array((1 , 5, 3))
print ("array created using passed tuple:\n", b)

array created using passed tuple:
 [1 5 3]


In [7]:
#7th program Creating array from list with type float
#importing Numpy Library

import numpy as np
a = np.array([[1, 3, 5], [4, 7, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [8]:
#8th program to create Array & print shape
#importing Numpy Library

import numpy as np
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Array is of type: ", type(array))
print("Shape of array: ", array.shape)

Array is of type:  <class 'numpy.ndarray'>
Shape of array:  (2, 4)
